# Generated by Django 5.2.16 on 2026-07-20 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('device_name', models.CharField(max_length=160)),
                ('device_class', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('기획', '기획'), ('개발', '개발'), ('검증', '검증'), ('인허가 준비', '인허가 준비'), ('완료', '완료'), ('중단', '중단')], default='개발', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('req_type', models.CharField(default='기능 요구사항', max_length=40)),
                ('source', models.CharField(default='내부 검토', max_length=40)),
                ('priority', models.CharField(default='중', max_length=10)),
                ('status', models.CharField(default='초안', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DesignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('design_type', models.CharField(default='소프트웨어', max_length=40)),
                ('status', models.CharField(default='초안', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('document_name', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='core.project')),
                ('requirements', models.ManyToManyField(blank=True, related_name='designs', to='core.requirement')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('hazard', models.CharField(max_length=200)),
                ('sequence', models.TextField(blank=True)),
                ('hazardous_situation', models.TextField(blank=True)),
                ('harm', models.TextField(blank=True)),
                ('probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('control', models.TextField(blank=True)),
                ('residual_probability', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_severity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_acceptable', models.BooleanField(default=False)),
                ('status', models.CharField(default='초안', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('designs', models.ManyToManyField(blank=True, related_name='risks', to='core.designitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.project')),
                ('requirements', models.ManyToManyField(blank=True, related_name='risks', to='core.requirement')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.TextField(blank=True)),
                ('precondition', models.TextField(blank=True)),
                ('procedure', models.TextField()),
                ('expected', models.TextField()),
                ('test_type', models.CharField(default='시스템시험', max_length=40)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.project')),
                ('requirements', models.ManyToManyField(blank=True, related_name='tests', to='core.requirement')),
                ('risks', models.ManyToManyField(blank=True, related_name='tests', to='core.risk')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('occurred_at', models.DateField()),
                ('description', models.TextField()),
                ('severity', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('investigation_status', models.CharField(default='접수', max_length=30)),
                ('reporting_review', models.CharField(default='검토 필요', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.project')),
                ('risks', models.ManyToManyField(blank=True, to='core.risk')),
                ('related_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.testcase')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual', models.TextField()),
                ('outcome', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('tested_at', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.testcase')),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('capa_type', models.CharField(default='시정 및 예방조치', max_length=30)),
                ('cause', models.TextField()),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='초안', max_length=30)),
                ('effectiveness_method', models.TextField(blank=True)),
                ('effectiveness_result', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='core.incident')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='core.project')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='core.risk')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='core.testcase')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
    ]
