# Generated by Django 5.2.16 on 2026-07-31 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_versionsnapshot_changerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('change_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_signature', to='core.changerequest')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-signed_at',),
            },
        ),
    ]
